"""
main.py

This file is the entry point of the entire system. The sequence of operations it executes is:
1. Initialises the Drone and the Ground Station 
2. RSA Public key exchange between the Drone and Ground Station
3. Authenticates the Drone with the Ground Station using CHAP-style authentication
4. Diffie Hellman key exchange, which is used for the Message Authentication Code
5. The AES session key is generated and exchanged securely using previously generated and shared RSA keys
6. The communication flow is simulated through the transmission of 3 message packets between Drone and Ground Station
7. After successful transmission of all messages, cyber attack simulations are performed - namely the replay and man-in-the-middle attacks
to show the system's robustness against these.
"""

from time import sleep

from drone import Drone
from ground_station import GroundStation
from tools import DroneMessage, DroneStatus
from attacks import ReplayAttacker, MITMAttacker

#Drone Configuration
DRONE_ID = "ALPHA_007"
SHARED_PASSWORD = "7thNe^erF@!ls"    #pre-shared password for authentication
MISSION_ID = "MISSION_SCOUT_V7"

#Helpers for the sequential execution of proper communication flow

def rsa_key_exchange(drone: Drone, gs: GroundStation) -> None:
    """
    Provides the Drone and Ground Station with each other's public keys. 
    """
    print("\nRSA Keys being exchanged between Drone and Ground Station...")
    sleep(1)
    drone.set_gs_public_key(gs.get_public_rsa_key())
    gs.enroll_drone_public_key(drone.get_public_rsa_key())
    print("RSA public keys exchanged and enrolled successfully.")

def drone_gs_authentication(drone: Drone, gs: GroundStation) -> None:
    """
    Authentication between the drone and ground station in a format same as the challenge handshake protocol.
    """
    print("\nTask 3.3 - Authentication (Challenge-Response Authentication being used)")
    print(f"Authenticating Drone {DRONE_ID}...")
    sleep(1)
    challenge = gs.issue_challenge()
    response = drone.respond_to_challenge(challenge)
    success = gs.verify_challenge_response(response)
    if not success:
        raise RuntimeError("Authentication failed - Rouge Drone identified. Aborting mission.") #Would run if the pre-shared passwords aren't the same.

def key_exchange(drone: Drone, gs: GroundStation) -> None:
    print("\nTask 3.1 - Diffie-Hellman Key Exchange")
    print("Diffie Hellman being used for Key Exchange...")
    sleep(1)
    drone_dh_public = drone.init_dh()
    gs_dh_public = gs.init_dh()
    # Each side independently derives the same shared MAC key
    drone.complete_dh(gs_dh_public)
    gs.complete_dh(drone_dh_public)
    sleep(1)
    print("Diffie-Hellman used for key-exchange used in MAC completed successfully.")

def aes_session_key(drone: Drone, gs: GroundStation) -> None:
    """
    AES Session key is generated by Drone and is received by Ground Station. Secure key exchange takes place using RSA.
    """
    print("\nTask 3.2 - AES Session Key Distribution using RSA (required RSA public keys shared previously)")
    print("Generating and sharing AES key...")
    sleep(1)
    encrypted_key = drone.generate_and_send_session_key() #Drone generates the AES key and shares it to GS. This procedure being followed to ensure Ground Station can handle multiple drones.
    gs.receive_session_key(encrypted_key)
    print("AES-256 session key securely transferred via RSA-OAEP.")

def message_transmission(drone: Drone, gs: GroundStation) -> None:
    """
    Simulates the message transmission, once all previous steps have completed and the Drone and Ground Station are prepared to communicate.
    """
    print("\nSession successfully established. Message Transmission now taking place from Drone to Ground Station.")
    print("\nCOMMUNICATION:")
    #Hard coded messages for the drone to transmit mid-flight
    messages = [
        DroneMessage(
            drone_id = DRONE_ID,
            position = (120.0, 80.0, 45.0),
            velocity = (3.5, 1.0, 0.0),
            battery_pct = 85.2,
            status = DroneStatus.FLYING,
            mission_id = MISSION_ID,
        ),
        DroneMessage(
            drone_id = DRONE_ID,
            position = (135.0, 82.0, 45.0),
            velocity = (0.0, 0.0, 0.0),
            battery_pct = 83.7,
            status = DroneStatus.HOVERING,
            mission_id = MISSION_ID,
        ),
        DroneMessage(
            drone_id = DRONE_ID,
            position = (135.0, 82.0, 5.0),
            velocity = (0.0, 0.0, -4.0),
            battery_pct = 81.1,
            status = DroneStatus.LANDING,
            mission_id = MISSION_ID,
        ),
    ]

    sent_packets = []
    for i, msg in enumerate(messages, start=1):
        print(f"\n[Packet {i}] Sending: {msg.printer()}")
        packet = drone.send_message(msg)
        sleep(1)
        print("[Packet on the wire]")
        print(f"    ciphertext : {packet['ciphertext'][:32]}...  (Total length: {len(packet['ciphertext'])} chars)")
        print(f"    aes_nonce  : {packet['aes_nonce']}")
        print(f"    mac        : {packet['mac'][:32]}...")
        print(f"    signature  : {packet['signature'][:32]}...  (Total length: {len(packet['signature'])} chars)")
        print(f"    msg_nonce  : {packet['msg_nonce']}")
        sleep(1)
        gs.receive_message(packet)
        print(f"Ground Station successfully received packet {i}")
        sent_packets.append(packet)
    return sent_packets

#Attack simulations
def simulate_replay_attack(gs: GroundStation, captured_packet: dict) -> None:
    """
    Simulates the Replay attack.
    """
    print("ATTACK SIMULATION 1 - REPLAY ATTACK")
    print("A cryptanalyst has captured packet #1 from the channel and tries re-submitting it to the Ground Station, creating a replay attack.\n")
    attacker = ReplayAttacker()
    attacker.capture(captured_packet) #We pass the first packet, which is considered to have been captured by the attacker
    attacker.attack(gs)

def simulate_mitm_attack(drone: Drone, gs: GroundStation) -> None:
    """
    Simulates the Man-in-the-Middle attack
    """
    print("ATTACK SIMULATION 2 - MAN-IN-THE-MIDDLE ATTACK")
    print("A cryptanalyst figured out the CHAP password and intercepts the DH exchange. She substitutes her own DH keys and forges a " \
        "new packet, signing it with her own RSA key (Drone's RSA key has not been figured out), and sends it.\n")
    #We take the existing Ground Station and Drone and use them directly, but under the setup that the cryptanalyst is now executing a 
    #mitm attack, by placing herself in the midst of the drone and the ground station.
    print("Cryptanalyst successfully begins impersonation by putting herself as an intermediary between the drone and the ground station...\n")
    attacker = MITMAttacker(SHARED_PASSWORD)
    attacker.attack(gs, mission=MISSION_ID)

def main() -> None:
    """
    Executes the entire communication system between the drone and the ground station. Also simulates the attacks and shows the
    system's capability to deal with them.
    """
    print("SECURE DRONE COMMUNICATION SYSTEM")
    print(f"Drone ID   : {DRONE_ID}")
    print(f"Mission    : {MISSION_ID}")
    print(f"Password   : {SHARED_PASSWORD}\n") #The password is used to initialise both drone and ground station and works for authenticating the devices and establishing the connection.

    #Initialise both drone and ground station.
    drone = Drone(DRONE_ID, SHARED_PASSWORD)
    ground_station = GroundStation(SHARED_PASSWORD) #Passwords passed to both drone and ground station - assume pre-defined.

    #The regular communication flow is executed.
    print("\nSESSION CREATION:")
    rsa_key_exchange(drone, ground_station)
    drone_gs_authentication(drone, ground_station)
    key_exchange(drone, ground_station)
    aes_session_key(drone, ground_station)
    packets = message_transmission(drone, ground_station)
    print("\nAll telemetry packets received, verified, and decrypted successfully.\nCOMPLETE COMMUNICATION SUCCESSFUL.\n")

    #Both replay and mitm attacks are simulated.
    simulate_replay_attack(ground_station, packets[0]) #Replay attack is simulated using the first accepted packet, which is assumed to be known to cryptanalyst.
    simulate_mitm_attack(drone, ground_station)

if __name__ == "__main__":
    main()
