"""
main.py
=======
Secure Drone Communication System - Demo Entry Point

Run with:   python main.py

Sequence
--------
1. Pre-mission provisioning  - RSA public key exchange
2. CHAP authentication       - drone proves identity to GCS
3. DH key exchange           - shared MAC key established
4. Session key distribution  - AES-256 key wrapped with RSA
5. Telemetry transmission    - multiple packets (shows nonce rotation)
6. Attack simulation 1       - Replay Attack       → BLOCKED
7. Attack simulation 2       - MITM Attack         → BLOCKED
"""

from time import sleep

from drone import Drone
from ground_station import GroundStation
from tools import DroneMessage, DroneStatus
from attacks import ReplayAttacker, MITMAttacker

#Drone Configuration
DRONE_ID = "ALPHA_007"
SHARED_PASSWORD = "7thNe^erF@!ls"    #pre-shared password for authentication
MISSION_ID = "MISSION_SCOUT_V7"

#Helpers for the sequential execution of proper communication flow

def rsa_key_exchange(drone: Drone, gcs: GroundStation) -> None:
    """
    Provides the Drone and Ground Station with each other's public keys. 
    """
    print("\nRSA Keys being exchanged between Drone and Ground Station...")
    sleep(1)
    drone.set_gcs_public_key(gcs.get_public_rsa_key())
    gcs.enroll_drone_public_key(drone.get_public_rsa_key())
    print("RSA public keys exchanged and enrolled successfully.")


def drone_gcs_authentication(drone: Drone, gcs: GroundStation) -> None:
    """
    Authentication between the drone and ground station in a format same as the challenge handshake protocol.
    """
    print("\nTask 3.3 - Authentication (Challenge-Response Authentication being used)")
    print(f"Authenticating Drone {DRONE_ID}...")
    sleep(1)
    challenge = gcs.issue_challenge()
    response = drone.respond_to_challenge(challenge)
    success = gcs.verify_challenge_response(response)
    if not success:
        raise RuntimeError("Authentication failed - Rouge Drone identified. Aborting mission.") #Would run if the pre-shared passwords aren't the same.

#NEEDS CHECKING
def key_exchange(drone: Drone, gcs: GroundStation) -> None:
    print("\nTask 3.1 - Diffie-Hellman Key Exchange")
    print("Diffie Hellman being used for Key Exchange...")
    sleep(1)
    drone_dh_pub = drone.init_dh()
    gcs_dh_pub = gcs.init_dh()
    # Each side independently derives the same shared MAC key
    drone.complete_dh(gcs_dh_pub)
    gcs.complete_dh(drone_dh_pub)
    print("Both sides derived the same shared secret independently.")


def aes_session_key(drone: Drone, gcs: GroundStation) -> None:
    """
    AES Session key is generated by Drone and is received by Ground Station. Secure key exchange takes place using RSA.
    """
    print("\nTask 3.2 - AES Session Key Distribution using RSA (required RSA public keys shared previously)")
    print("Generating and sharing AES key...")
    sleep(1)
    encrypted_key = drone.generate_and_send_session_key() #Drone generates the AES key and shares it to GCS. This procedure being followed to ensure Ground Station can handle multiple drones.
    gcs.receive_session_key(encrypted_key)
    print("AES-256 session key securely transferred via RSA-OAEP.")


def message_transmission(drone: Drone, gcs: GroundStation) -> None:
    """
    Simulates the message transmission, once all previous steps have completed and the Drone and Ground Station are prepared to communicate.
    """
    print("\nMessage Transmission taking place from Drone to Ground Station:")
    #Hard coded messages for the drone to transmit mid-flight
    messages = [
        DroneMessage(
            drone_id = DRONE_ID,
            position = (120.0, 80.0, 45.0),
            velocity = (3.5, 1.0, 0.0),
            battery_pct = 85.2,
            status = DroneStatus.FLYING,
            mission_id = MISSION_ID,
        ),
        DroneMessage(
            drone_id = DRONE_ID,
            position = (135.0, 82.0, 45.0),
            velocity = (0.0, 0.0, 0.0),
            battery_pct = 83.7,
            status = DroneStatus.HOVERING,
            mission_id = MISSION_ID,
        ),
        DroneMessage(
            drone_id = DRONE_ID,
            position = (135.0, 82.0, 5.0),
            velocity = (0.0, 0.0, -4.0),
            battery_pct = 81.1,
            status = DroneStatus.LANDING,
            mission_id = MISSION_ID,
        ),
    ]

    sent_packets = []
    for i, msg in enumerate(messages, start=1):
        print(f"\n[Packet {i}] Sending: {msg.printer()}")
        packet = drone.send_message(msg)
        sleep(1)
        print("[Packet on the wire]")
        print(f"    ciphertext : {packet['ciphertext'][:32]}...  (Total length: {len(packet['ciphertext'])} chars)")
        print(f"    aes_nonce  : {packet['aes_nonce']}")
        print(f"    mac        : {packet['mac'][:32]}...")
        print(f"    signature  : {packet['signature'][:32]}...  (Total length: {len(packet['signature'])} chars)")
        print(f"    msg_nonce  : {packet['msg_nonce']}")
        sleep(1)
        gcs.receive_message(packet)
        print(f"Ground Station successfully received packet {i}")
        sent_packets.append(packet)
    return sent_packets


#Attack simulations
def simulate_replay_attack(gcs: GroundStation, captured_packet: dict) -> None:
    """
    Simulates the Replay attack.
    """
    print("ATTACK SIMULATION 1 - REPLAY ATTACK")
    print("A cryptanalyst has captured packet #1 from the channel and tries re-submitting it to the Ground Station, creating a replay attack.\n")
    attacker = ReplayAttacker()
    attacker.capture(captured_packet)
    attacker.attack(gcs)


def simulate_mitm_attack() -> None:
    """
    Simulates the Man-in-the-Middle attack
    """
    print("ATTACK SIMULATION 2 - MAN-IN-THE-MIDDLE ATTACK")
    print("A cryptanalyst figured out the CHAP password and intercepts the DH exchange. She substitutes her own DH keys and forges a " \
        "new packet, signing it with her own RSA key (Drone's RSA key has not been figured out), and sends it.\n")

    # Fresh GCS with the REAL drone's public key enrolled
    real_drone = Drone(DRONE_ID, SHARED_PASSWORD)
    fresh_gcs = GroundStation(SHARED_PASSWORD)

    # Pre-mission: GCS enrolls the real drone's RSA public key
    fresh_gcs.enroll_drone_public_key(real_drone.get_public_rsa_key())
    print(f"\n  [Setup] Fresh GCS created; real Drone '{DRONE_ID}' RSA key enrolled.")
    print("  [Setup] Cryptanalyst begins impersonation...\n")

    # Eve knows the password, has her own RSA keypair, and intercepts DH
    attacker = MITMAttacker(SHARED_PASSWORD)
    attacker.attack(fresh_gcs, real_drone_mission_id=MISSION_ID)


def main() -> None:
    """
    Executes the entire communication system between the drone and the ground station. Also simulates the attacks and shows the
    system's capability to deal with them.
    """

    print("SECURE DRONE COMMUNICATION SYSTEM")
    print(f"Drone ID   : {DRONE_ID}")
    print(f"Mission    : {MISSION_ID}")
    print(f"Password   : {SHARED_PASSWORD}\n") #The password is used to initialise both drone and ground station and works for authenticating the devices and establishing the connection.

    #Initialise both drone and ground station.
    drone = Drone(DRONE_ID, SHARED_PASSWORD)
    ground_station = GroundStation(SHARED_PASSWORD) #Passwords passed to both drone and ground station - assume pre-defined.

    #The regular communication flow is executed.
    print("\nCOMMUNICATION:")
    rsa_key_exchange(drone, ground_station)
    drone_gcs_authentication(drone, ground_station)
    key_exchange(drone, ground_station)
    aes_session_key(drone, ground_station)
    packets = message_transmission(drone, ground_station)
    print("\nAll telemetry packets received, verified, and decrypted successfully.\nCOMPLETE COMMUNICATION SUCCESSFUL.\n")

    #Both replay and mitm attacks are simulated.
    simulate_replay_attack(ground_station, packets[0]) #Replay attack is simulated using the first accepted packet, which is assumed to be known to cryptanalyst.
    simulate_mitm_attack()

if __name__ == "__main__":
    main()
