"""
tools/encryption.py
===================
Hybrid Encryption: RSA-OAEP  +  AES-256-CTR

Why hybrid?
-----------
RSA is computationally expensive and can only encrypt small payloads.
AES-CTR is fast and handles arbitrary-length data.
The hybrid scheme combines the key-distribution strength of RSA with
the throughput of AES:
    1. Drone generates a fresh random AES-256 session key.
    2. Drone encrypts the session key with the GCS's RSA public key.
    3. Drone encrypts the actual telemetry data with AES-256-CTR.
    4. GCS decrypts the session key with its RSA private key.
    5. GCS decrypts the telemetry data with the recovered session key.

AES-CTR mode
------------
CTR (Counter) mode turns AES into a stream cipher — no padding required,
and every 16-byte block is encrypted independently.  A fresh 16-byte
nonce is generated per message and transmitted alongside the ciphertext.

Classes
-------
HybridEncryptor — stateless; all methods are static helpers.
"""

import os
from cryptography.hazmat.primitives.asymmetric import padding as asym_padding
from cryptography.hazmat.primitives.asymmetric.rsa import RSAPublicKey, RSAPrivateKey
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives import hashes

class HybridEncryptor:
    # OAEP padding used for RSA encryption/decryption of the AES key - CHECK HERE
    OAEP = asym_padding.OAEP(mgf=asym_padding.MGF1(algorithm=hashes.SHA256()),  algorithm=hashes.SHA256(), label=None)

    @staticmethod
    def rsa_encrypt_key(aes_key: bytes, rsa_public_key: RSAPublicKey) -> bytes:
        """
        Wraps an AES session key (generated by the Drone in this implementation) with a RSA public key, for secure sharing.
        """
        return rsa_public_key.encrypt(aes_key, HybridEncryptor.OAEP)

    @staticmethod
    def rsa_decrypt_key(encrypted_key: bytes, rsa_private_key: RSAPrivateKey) -> bytes:
        """
        Unwrap an AES key, which was previously wrapped, with the corresponding RSA private key. Implements secure key sharing of the
        symmetric cryptographic algorithm AES.
        """
        return rsa_private_key.decrypt(encrypted_key, HybridEncryptor.OAEP)

    @staticmethod
    def aes_encrypt(plaintext: bytes, aes_key: bytes) -> tuple[bytes, bytes]:
        """
        Encrypts the plaintext using the AES session key. It also generates an AES nonce, returning both ciphertext and aes nonce.
        """
        ctr_nonce = os.urandom(16)
        cipher = Cipher(algorithms.AES(aes_key), modes.CTR(ctr_nonce))
        enc = cipher.encryptor()
        ciphertext = enc.update(plaintext) + enc.finalize()
        return ciphertext, ctr_nonce

    @staticmethod
    def aes_decrypt(ciphertext: bytes, aes_key: bytes, ctr_nonce: bytes) -> bytes:
        """
        Decrypts the previously generated ciphertext using the AES session key and returns the original plaintext.
        """
        cipher = Cipher(algorithms.AES(aes_key), modes.CTR(ctr_nonce))
        dec = cipher.decryptor()
        return dec.update(ciphertext) + dec.finalize()
