"""
encryption.py

This file goes through the entire procedure of encryption of a message, and also the corresponding decryption. It follows a hybrid
encryption scheme, combining both AES and RSA techniques, trying to get the best of both symmetric and asymmetrics cryptographic
techniques. The procedure followed is:
1. RSA public keys of Drone and Ground Station are assumed to be shared with each other before proceeding.
2. The Drone generates an AES session key and encrypts it using the RSA public key of the Ground Station, upon which this message is
transmitted to the ground station.
4. The Ground Station decrypts the session key using its own RSA private key.
5. It then proceeds to use this decrypted AES session key to decrypt the ciphertext in order to obtain the plaintext.
RSA, an asymmetric key algorithm, although has advantages in terms of a few security and key sharing aspects, is extremely expensive to
implement, even more so in a continuous, long communication, like in the given scenario. A symmetric key technique like AES is significantly
better, faster and more efficient, but suffers from key-exchange disadvantages. Therefore, applying a hybrid implementation of cryptographic
techniques, by using RSA to encrypt only the actual AES key, which is used for encryption the plaintext message, is the best method, effectively
using advantages of both techniques. In this implementation, we are using the AES counter (CTR) mode, which is generally considered to be 
the best operating mode of block ciphers.
"""

import os
from cryptography.hazmat.primitives.asymmetric import padding as asym_padding
from cryptography.hazmat.primitives.asymmetric.rsa import RSAPublicKey, RSAPrivateKey
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives import hashes

class HybridEncryptor:
    #OAEP is a commonly used padding configuration used for RSA encryption/decryption of the AES key
    OAEP = asym_padding.OAEP(mgf=asym_padding.MGF1(algorithm=hashes.SHA256()),  algorithm=hashes.SHA256(), label=None)

    @staticmethod
    def rsa_encrypt_key(aes_key: bytes, rsa_public_key: RSAPublicKey) -> bytes:
        """
        Wraps an AES session key (generated by the Drone in this implementation) with a RSA public key, for secure sharing.
        """
        return rsa_public_key.encrypt(aes_key, HybridEncryptor.OAEP)

    @staticmethod
    def rsa_decrypt_key(encrypted_key: bytes, rsa_private_key: RSAPrivateKey) -> bytes:
        """
        Unwrap an AES key, which was previously wrapped, with the corresponding RSA private key. Implements secure key sharing of the
        symmetric cryptographic algorithm AES.
        """
        return rsa_private_key.decrypt(encrypted_key, HybridEncryptor.OAEP)

    @staticmethod
    def aes_encrypt(plaintext: bytes, aes_key: bytes) -> tuple[bytes, bytes]:
        """
        Encrypts the plaintext using the AES session key. It also generates an AES nonce, returning both ciphertext and aes nonce.
        """
        ctr_nonce = os.urandom(16)
        cipher = Cipher(algorithms.AES(aes_key), modes.CTR(ctr_nonce))
        enc = cipher.encryptor()
        ciphertext = enc.update(plaintext) + enc.finalize()
        return ciphertext, ctr_nonce

    @staticmethod
    def aes_decrypt(ciphertext: bytes, aes_key: bytes, ctr_nonce: bytes) -> bytes:
        """
        Decrypts the previously generated ciphertext using the AES session key and returns the original plaintext.
        """
        cipher = Cipher(algorithms.AES(aes_key), modes.CTR(ctr_nonce))
        dec = cipher.decryptor()
        return dec.update(ciphertext) + dec.finalize()
